#!/bin/bash

# Quick Telnyx Webhook Setup Script
# This helps you configure your Telnyx webhooks for production

echo "🔧 Telnyx Webhook Configuration Helper"
echo "========================================"
echo ""

# Get server URL
read -p "Enter your server URL (e.g., https://yourdomain.com): " SERVER_URL

if [ -z "$SERVER_URL" ]; then
    echo "❌ Server URL is required!"
    exit 1
fi

WEBHOOK_URL="${SERVER_URL}/api/webhooks/telnyx"

echo ""
echo "✅ Your webhook configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Webhook URL (copy this):"
echo "   ${WEBHOOK_URL}"
echo ""
echo "📋 Required Webhook Events to Enable:"
echo "   ✓ call.initiated"
echo "   ✓ call.answered"
echo "   ✓ call.hangup"
echo "   ✓ call.recording.saved (optional)"
echo "   ✓ call.recording.available (optional)"
echo ""
echo "⚙️  Configuration Steps:"
echo ""
echo "1. Go to: https://portal.telnyx.com/#/app/call-control/applications"
echo ""
echo "2. Select your Call Control Application"
echo ""
echo "3. Set Webhook URL to:"
echo "   ${WEBHOOK_URL}"
echo ""
echo "4. Set Webhook API Version: V2"
echo ""
echo "5. Enable the webhook events listed above"
echo ""
echo "6. Enable Call Recording:"
echo "   - Go to Application Settings"
echo "   - Enable 'Record Calls'"
echo "   - Format: MP3 (recommended)"
echo "   - Channels: Single or Dual"
echo ""
echo "7. Enable AI Assistant (if using):"
echo "   - Go to AI & Voice section"
echo "   - Configure your AI Assistant"
echo "   - Enable Transcription"
echo "   - Enable Sentiment Analysis"
echo ""
echo "8. Save all changes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 Test Your Setup:"
echo ""
echo "1. Make a test call to your Telnyx number"
echo ""
echo "2. Check server logs:"
echo "   pm2 logs call-insights-hub"
echo ""
echo "3. Look for webhook events in logs:"
echo "   📥 Telnyx Webhook Received"
echo "   📞 Telnyx Event: call.initiated"
echo "   ✅ Call logged to database"
echo ""
echo "4. View calls in your app:"
echo "   - Navigate to 'Call History' section"
echo "   - Click 'Refresh' or 'Sync from Telnyx'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📞 Telnyx API Key Check:"
if [ -n "$TELNYX_API_KEY" ]; then
    echo "   ✅ TELNYX_API_KEY is set"
else
    echo "   ⚠️  TELNYX_API_KEY not found in environment"
    echo "   Add to .env file: TELNYX_API_KEY=your_key_here"
fi
echo ""
echo "💡 Troubleshooting:"
echo "   - Webhooks not working? Check firewall and server accessibility"
echo "   - Calls not appearing? Verify webhook URL is correct"
echo "   - No recordings? Enable recording in Telnyx application"
echo "   - Check logs: pm2 logs call-insights-hub"
echo ""
echo "📚 Full Documentation: /root/Inbound-Agent-Tracking-Analytics/CALL_HISTORY_GUIDE.md"
echo ""
